### ISSUE TITLE
Definición del proyecto

### ISSUE THREAD

**Issue by Brayhan208** [Brayhan208/SABPPIO5#1]
Nuestro proyecto se podría definir como una idea que busca ayudar a las personas que quieren una empezar o que tienen dificultades para empezar en el mundo deportivo, esta aplicación le daría  la información necesaria que cada usuario necesite esto se buscaría lograr con un algoritmo que se adapte a las preferencias de cada usuario.

**Comment by Brayhan208** [comment]
Nuestro proyecto se podría definir como una idea que busca ayudar a las personas que quieren una empezar o que tienen dificultades para empezar en el mundo deportivo, esta aplicación le daría  la información necesaria que cada usuario necesite esto se buscaría lograr con un algoritmo que se adapte a las preferencias de cada usuario

**Comment by juanperezu** [comment]
"Nuestro proyecto se podría definir como una idea que busca ayudar a las personas que quieren una empezar o que tienen dificultades para empezar en el mundo deportivo, esta aplicación le daría la información necesaria que cada usuario necesite esto se buscaría lograr con un algoritmo que se adapte a las preferencias de cada usuario._"

**Corregir**
**"Brindar** información a aquellas personas que desean practicar un deporte de acuerdo a sus necesidades"
